### ISSUE TITLE
How To install it

### ISSUE THREAD

**Issue by tvserial** [dhavalhariyani/hs-widevine#2]
I cant install it..google module not found showing...help

**Comment by parnexcodes** [comment]
pip install google-api-python-client

**Comment by tvserial** [comment]
> pip install google-api-python-client

Parnnex this script still work?? we know google old cdm revoked...this script has L1 CDM?

**Comment by wade29** [comment]
where to enter mpd, video link and output ? please send image for ref. I get below error.

C:\Program Files\Python36\python hotstar_github.py
usage: hotstar_github.py [-h] -mpd MPD -o OUTPUT [-keys]
hotstar_github.py: error: the following arguments are required: -mpd/--video-link, -o/--output

**Comment by anonyymous2021** [comment]
> where to enter mpd, video link and output ? please send image for ref. I get below error.

Me too

**Comment by anonyymous2021** [comment]
I got this error :(

  File "C:\Python36\hs-widevine-main\hotstar_github.py", line 34, in <module>
    subprocess.run([youtubedlexe, '-k', '--user-agent', 'KAIOS/2.0', '-F', MPD])
  File "C:\Python36\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python36\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python36\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

**Comment by anonyymous2021** [comment]
> 
> 
> where to enter mpd, video link and output ? please send image for ref. I get below error.
> 
> C:\Program Files\Python36\python hotstar_github.py
> usage: hotstar_github.py [-h] -mpd MPD -o OUTPUT [-keys]
> hotstar_github.py: error: the following arguments are required: -mpd/--video-link, -o/--output

You have to put it like this 
hotstar_github.py [-h] -mpd LINK MPD HERE -o OUTPUT (Here I do not know if it is a name or a starting address ) [-keys]

**Comment by saidekrishna** [comment]
how do i get keys???

**Comment by MG577** [comment]
@dhavalhariyani I know currently theres no working CDM .. but is this error related to CDM ???


Enter Decryption Section...
usage: mp4dump [-h] FILE
mp4dump: error: argument FILE: can't open 'output': [Errno 13] Permission denied: 'output'
Traceback (most recent call last):
  File "D:\Latest Films\Download Tools\hs-widevine-main\hs-widevine-main\hs-widevine-main\hs-widevine-main\hotstar.py", line 108, in <module>
    pssh_mpd = Get_PSSH(FInput_audio)
  File "D:\Latest Films\Download Tools\hs-widevine-main\hs-widevine-main\hs-widevine-main\hs-widevine-main\hotstar.py", line 94, in Get_PSSH
    data = subprocess.check_output([mp4dump, '--format', 'json', '--verbosity', '1', mp4_file])
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by dhavalhariyani** [comment]
This error is saying that there was error opening file for output. You must
be running the script as administrator/root and the permission to
read-write is needed.

**Comment by MG577** [comment]
@dhavalhariyani 

how to do that bro .. cant find that run as admin (on windows)


bro can u do something to ur script 
theres a modified pywidevine 

**https://github.com/T3rry7f/NoDRM/tree/master/PywidevineX**

it says 

**For Chromecdm 2209 private key is not necessary, directly using the rsa whitebox crypto instead.**

**Comment by MG577** [comment]
> This error is saying that there was error opening file for output. You must be running the script as administrator/root and the permission to read-write is needed.

how to solve the error bro ... waiting for ur reply

**Comment by arbarbosa1979** [comment]
> > This error is saying that there was error opening file for output. You must be running the script as administrator/root and the permission to read-write is needed.
> 
> how to solve the error bro ... waiting for ur reply

This script is no longer working, but its errors were basically: 

- 1 - You used spaces in the folder names where the python scripts are, don't use spaces in the folder names.
--> `D:\Latest Films\Download Tools\`

- 2 - To run the script as administrator, just open CMD as administrator, the simplest thing in the world.
--> [https://stackoverflow.com/questions/49404561/hotkey-to-open-cmd-with-administration-rights-in-current-folder-from-explorer](https://stackoverflow.com/questions/49404561/hotkey-to-open-cmd-with-administration-rights-in-current-folder-from-explorer)

- 3 - how to use was just looking at the source code of the python script `hotstar.py`:
`python hotstar.py -h`
`python hotstar.py -mpd link to mpd -o filename`

-mpd --> mpd manifest link
-o --> filename without spaces and without extension, example: -o Mulan_1998

- 4 - If you don't know what **mpd** is, you shouldn't even be trying to use this script.

**Comment by fpalacio78** [comment]
I have a problem using this script, I would really appreciate the help 
the mpd is https://dramax-vod.ercdn.net/clr/Y/vl/gunesin-kizlari-s1-b2-spa/gunesin-kizlari-s1-b2-spa.smil/manifest_mpm4sav_mvnumber_high.mpd 
`PS C:\Users\ADMINPC\Downloads\hs-widevine-main\hs-widevine-main> python hotstar.py -mpd https://dramax-vod.ercdn.net/clr/Y/vl/gunesin-kizlari-s1-b2-spa/gunesin-kizlari-s1-b2-spa.smil/manifest_mpm4sav_mvnumber_high.mpd -o video
Traceback (most recent call last):
  File "C:\Users\ADMINPC\Downloads\hs-widevine-main\hs-widevine-main\hotstar.py", line 34, in <module>
    subprocess.run([youtubedlexe, '-k', '--user-agent', 'KAIOS/2.0', '-F', MPD])
  File "C:\Users\ADMINPC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\ADMINPC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ADMINPC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file
specified 
PS C:\Users\ADMINPC\Downloads\hs-widevine-main\hs-widevine-main>`

**Comment by arbarbosa1979** [comment]
> I have a problem using this script, I would really appreciate the help the mpd is https://dramax-vod.ercdn.net/clr/Y/vl/gunesin-kizlari-s1-b2-spa/gunesin-kizlari-s1-b2-spa.smil/manifest_mpm4sav_mvnumber_high.mpd `PS C:\Users\ADMINPC\Downloads\hs-widevine-main\hs-widevine-main> python hotstar.py -mpd https://dramax-vod.ercdn.net/clr/Y/vl/gunesin-kizlari-s1-b2-spa/gunesin-kizlari-s1-b2-spa.smil/manifest_mpm4sav_mvnumber_high.mpd -o video Traceback (most recent call last): File "C:\Users\ADMINPC\Downloads\hs-widevine-main\hs-widevine-main\hotstar.py", line 34, in <module> subprocess.run([youtubedlexe, '-k', '--user-agent', 'KAIOS/2.0', '-F', MPD]) File "C:\Users\ADMINPC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\ADMINPC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\ADMINPC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified PS C:\Users\ADMINPC\Downloads\hs-widevine-main\hs-widevine-main>`

Did you put these files in the system path or in the same folder as the python script?

---> _yt-dlp, ffmpeg, aria2c, mp4decrypt, mkvmerge and mp4dump_.

yt-dlp you can install by running this command: `pip install yt-dlp`

**Comment by maanich** [comment]
ecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Iterable
Traceback (most recent call last):
  File "/usr/bin/py", line 167, in <module>
    result = eval(args.expression)
  File "<string>", line 1, in <module>
    l3.py
NameError: name 'l3' is not defined
